// Generated by CoffeeScript 1.6.3
(function() {
  var ChatSchema, UserSchema, mongoose;

  mongoose = require('mongoose');

  ChatSchema = new mongoose.Schema({
    title: String,
    users: [
      {
        type: mongoose.Schema.ObjectId,
        ref: 'user'
      }
    ],
    messages: []
  });

  UserSchema = new mongoose.Schema({
    name: String,
    color: String,
    chats: [
      {
        type: mongoose.Schema.ObjectId,
        ref: 'chat'
      }
    ]
  });

  module.exports = {
    Chat: mongoose.model('chat', ChatSchema),
    User: mongoose.model('user', UserSchema)
  };

}).call(this);
